services:
  - type: web
    name: flask-app
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.8.9"
    buildCommand: |
      pyenv install 3.8.9 --skip-existing
      pyenv global 3.8.9
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
